name: Release
on:
  push:
    tags:
      # tag 格式为 vA.B.C
      - 'v*.*.*'

jobs:
  publishGitRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - name: Build
        run: make && tar -zcvf pushgateway.tar.gz pushgateway*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # name: Name of the release. defaults to tag name
          # body_path: Path to load text communicating notable changes in this release
          # target_commitish: Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Defaults to repository default branch.
          # Newline-delimited globs of paths to assets to upload for release
          files: pushgateway.tar.gz
          fail_on_unmatched_files: true
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo.
          # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          # Name of a target repository in <owner>/<repo> format. Defaults to GITHUB_REPOSITORY env variable
          # repository: <another_owner>/<another_repo>